### ISSUE TITLE
Сломалась сборка прошивки

### ISSUE THREAD

**Issue by kilroy98** [shvchk/padavan-builder-workflow#42]
```
Starting job container
  /usr/bin/docker pull registry.gitlab.com/hadzhioglu/padavan-ng
  Using default tag: latest
  Error response from daemon: manifest for registry.gitlab.com/hadzhioglu/padavan-ng:latest not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 1.628 seconds before retry.
  /usr/bin/docker pull registry.gitlab.com/hadzhioglu/padavan-ng
  Using default tag: latest
  Error response from daemon: manifest for registry.gitlab.com/hadzhioglu/padavan-ng:latest not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 9.902 seconds before retry.
  /usr/bin/docker pull registry.gitlab.com/hadzhioglu/padavan-ng
  Using default tag: latest
  Error response from daemon: manifest for registry.gitlab.com/hadzhioglu/padavan-ng:latest not found: manifest unknown: manifest unknown
  Error: Docker pull failed with exit code 1
```

P.S. И думаю стоит отключить "Pull requests", всё равно они не нужны и чтобы не засоряли ими.

**Comment by clickerpw** [comment]
[build](https://github.com/clickerpw/padavan-builder-workflow/actions/runs/8567310992/job/23478840988#step:2:29)
Docker pull failed with exit code 1
[build](https://github.com/clickerpw/padavan-builder-workflow/actions/runs/8567310992/job/23478840988#step:2:21)
Docker pull failed with exit code 1, back off 8.846 seconds before retry.
[build](https://github.com/clickerpw/padavan-builder-workflow/actions/runs/8567310992/job/23478840988#step:2:25)
Docker pull failed with exit code 1, back off 5.804 seconds before retry.

**Comment by Crocodil1976** [comment]
Да, прошивка не собирается. Похоже докер поломался.

**Comment by shvchk** [comment]
В качестве временной меры можно использовать контейнер из моего репо, только что синхронизировал с репо Сергея и собрал. Для этого замените в `.github/workflows/build.yml` на 12 строке `registry.gitlab.com/hadzhioglu/padavan-ng` на `registry.gitlab.com/a-shevchuk/padavan-ng`

**Comment by Crocodil1976** [comment]
Ответ Сергея:

Добрый день. Да вчера очищал и по ошибке удалил, исправлю. Спасибо большое.

Так что ждем.

Временное решение работает
