### ISSUE TITLE
Не собирается прошивка. 

### ISSUE THREAD

**Issue by maksimum380** [shvchk/padavan-builder-workflow#51]
Пишет нет файлов в репозитории
cp: -r not specified; omitting directory 'padavan-ng/trunk/images/'
Прилагаю фото 
![Screenshot_20240602-214143_Chrome](https://github.com/shvchk/padavan-builder-workflow/assets/80404685/8292321b-45fb-49b8-ba32-09d8d8127315)
Можете както исправить?

**Comment by Frew777** [comment]
У меня такая же проблема 
![Screenshot_296](https://github.com/shvchk/padavan-builder-workflow/assets/96523750/4db4981a-fd2c-4407-8ccd-77752f8d2c45)

**Comment by Frew777** [comment]
В общем убрал из прошивки MINIDLNA и прошивка удачно собралась
![image](https://github.com/shvchk/padavan-builder-workflow/assets/96523750/d165c9da-02b7-4821-9396-1cb35d4b4e73)
![image](https://github.com/shvchk/padavan-builder-workflow/assets/96523750/5c07b169-196f-4762-ad2d-7e5a462b68f5)
